export enum Asset {
  ETHv1 = "ETHv1",
  ETH = "ETH",
  WETH = "WETH",
  fWETH = "fWETH",
  SAI = "SAI",
  DAI = "DAI",
  CHAI = "CHAI",
  USDC = "USDC",
  USDT = "USDT",
  SUSD = "SUSD",
  WBTC = "WBTC",
  LINK = "LINK",
  MKR = "MKR",
  ZRX = "ZRX",
  BAT = "BAT",
  REP = "REP",
  KNC = "KNC",
  CHI = "CHI",
  LEND = "LEND",
  BZRX = "BZRX",
  YFI = "YFI",
  UNKNOWN = "UNKNOWN"
}
