export enum Asset {
  ETH = 'ETH',
  WETH = 'WETH',
  fWETH = 'fWETH',
  SAI = 'SAI',
  DAI = 'DAI',
  CHAI = 'CHAI',
  USDC = 'USDC',
  USDT = 'USDT',
  SUSD = 'SUSD',
  WBTC = 'WBTC',
  LINK = 'LINK',
  MKR = 'MKR',
  ZRX = 'ZRX',
  BAT = 'BAT',
  REP = 'REP',
  LEND = 'LEND',
  KNC = 'KNC',
  CHI = 'CHI',
  BZRX = 'BZRX',
  YFI = 'YFI',
  UNI = 'UNI',
  AAVE = 'AAVE',
  UNKNOWN = 'UNKNOWN'
}
