[build]
  publish = "build"
  command = "yarn build"
  ignore = "git diff --quiet \"${CACHED_COMMIT_REF}\" \"${COMMIT_REF}\" . ../../yarn.lock ../bzx-common"
  environment = { CI = '', NETLIFY_USE_YARN = "true", DISABLE_ESLINT_PLUGIN = "true" }
